import "./regular";
import "./lazy";
import "./multi";
import "./lazy-multi";
import "./singleton";
import "./transient";
import "./deep-level";
import "./type-hierarchy.1";
import "./type-hierarchy.2";